# Generated by Django 5.2.17 on 2026-10-08 02:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=30, unique=True, verbose_name='タグ名')),
            ],
            options={
                'db_table': 'TAG',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(db_column='LOGIN_ID', max_length=30, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='ログインID')),
                ('password', models.CharField(db_column='PASSWORD', max_length=128, verbose_name='パスワード')),
                ('display_name', models.CharField(db_column='DISPLAY_NAME', max_length=10, verbose_name='ユーザーネーム')),
                ('is_public', models.BooleanField(db_column='IS_PUBLIC', default=True, verbose_name='公開設定')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'USERS',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_column='TITLE', max_length=50, verbose_name='タイトル')),
                ('posted_at', models.DateTimeField(auto_now_add=True, db_column='POSTED_AT', verbose_name='投稿日時')),
                ('trip_start_date', models.DateField(db_column='TRIP_START_DATE', verbose_name='旅行開始日')),
                ('trip_end_date', models.DateField(db_column='TRIP_END_DATE', verbose_name='旅行終了日')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UPDATED_AT', verbose_name='更新日時')),
                ('user', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'db_table': 'LOG',
            },
        ),
        migrations.CreateModel(
            name='Logcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(blank=True, db_column='IMAGE_PATH', max_length=255, null=True, verbose_name='画像パス')),
                ('taken_at', models.DateTimeField(blank=True, db_column='TAKEN_AT', null=True, verbose_name='撮影日時')),
                ('latitude', models.FloatField(blank=True, db_column='LATITUDE', null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, db_column='LONGITUDE', null=True, verbose_name='経度')),
                ('comment', models.TextField(db_column='COMMENT', verbose_name='コメント')),
                ('display_order', models.IntegerField(db_column='DISPLAY_ORDER', verbose_name='表示順番号')),
                ('log', models.ForeignKey(db_column='LOG_ID', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='routrip.log', verbose_name='ログ')),
            ],
            options={
                'db_table': 'LOGCARD',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='thumbnail_card',
            field=models.ForeignKey(blank=True, db_column='THUMBNAIL_CARD_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumbnail_logs', to='routrip.logcard', verbose_name='サムネイルカード'),
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='NAME', max_length=30, verbose_name='スポット名')),
                ('latitude', models.FloatField(db_column='LATITUDE', verbose_name='緯度')),
                ('longitude', models.FloatField(db_column='LONGITUDE', verbose_name='経度')),
                ('registered_user', models.ForeignKey(db_column='REGISTERED_USER_ID', on_delete=django.db.models.deletion.PROTECT, related_name='registered_spots', to=settings.AUTH_USER_MODEL, verbose_name='登録者')),
            ],
            options={
                'db_table': 'SPOT',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_order', models.IntegerField(db_column='SECTION_ORDER', verbose_name='区間順序')),
                ('transport', models.CharField(db_column='TRANSPORT', max_length=10, verbose_name='移動手段')),
                ('duration', models.IntegerField(blank=True, db_column='DURATION_MIN', null=True, verbose_name='所要時間（分）')),
                ('log', models.ForeignKey(db_column='LOG_ID', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='routrip.log', verbose_name='ログ')),
                ('from_spot', models.ForeignKey(db_column='START_SPOT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='departing_sections', to='routrip.spot', verbose_name='出発スポット')),
                ('to_spot', models.ForeignKey(db_column='TO_SPOT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='arriving_sections', to='routrip.spot', verbose_name='到着スポット')),
            ],
            options={
                'db_table': 'SEGMENT',
            },
        ),
        migrations.AddField(
            model_name='logcard',
            name='spot',
            field=models.ForeignKey(db_column='SPOT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='log_cards', to='routrip.spot', verbose_name='スポット'),
        ),
        migrations.AddField(
            model_name='log',
            name='start_spot',
            field=models.ForeignKey(db_column='START_SPOT_ID', on_delete=django.db.models.deletion.PROTECT, related_name='start_logs', to='routrip.spot', verbose_name='出発スポット'),
        ),
        migrations.AddField(
            model_name='log',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='logs', to='routrip.tag', verbose_name='タグ'),
        ),
    ]
