# Generated by Django 5.2.17 on 2026-10-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcard',
            name='image_path',
            field=models.CharField(blank=True, db_column='IMAGE_PATH', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='PASSWORD', max_length=128),
        ),
    ]
