# Generated by Django 5.2.17 on 2026-10-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routrip', '0003_alter_logcard_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logcard',
            name='image_path',
            field=models.ImageField(blank=True, db_column='IMAGE_PATH', max_length=255, null=True, upload_to='photos/', verbose_name='画像'),
        ),
    ]
